# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
workflows:
  version: 2
  test_build:
      jobs:
        - test
        - dockerize:
            requires:
              - test

jobs:
  test:
    docker:  
      # docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: chandrarai/pythonapp:latest
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    steps:
      - checkout

      - run: 
           name: Run the python command
           command: 
              python tests.py
             
      - store_artifacts:
           path: .
           destination: test_output
             
  dockerize:
    machine: true
    steps:
      - checkout
      # Login to docker
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS

      # build the application image
      - run: docker build -t $DOCKER_USER/myapp:$CIRCLE_SHA1 .

      # deploy the image
      - run: docker push $DOCKER_USER/myapp:$CIRCLE_SHA1
